# Generated by Django 5.1.2 on 2024-12-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0003_disease_amount_disease_area_disease_protect_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disease",
            old_name="severinty",
            new_name="severity",
        ),
        migrations.AlterField(
            model_name="disease",
            name="amount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="area",
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
