# Generated by Django 5.1.5 on 2025-01-24 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0006_disease_user_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
