# Generated by Django 5.1.5 on 2025-01-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0007_disease_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='user',
        ),
    ]
