# Generated by Django 5.1.5 on 2025-01-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0009_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
