# Generated by Django 5.1.5 on 2025-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0010_alter_disease_amount_alter_disease_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
    ]
