# Generated by Django 5.1.5 on 2025-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0011_nearbyshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=80, unique=True)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
