# Generated by Django 5.1.5 on 2025-02-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0012_marketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalHarvesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.JSONField(blank=True, default=list)),
                ('techniques', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='MarketPrice',
        ),
    ]
