# Generated by Django 5.1.5 on 2025-02-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0014_crop_season_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='crop',
        ),
        migrations.CreateModel(
            name='CropRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growing_periods', models.JSONField(default=list)),
                ('suitable_months', models.JSONField(default=list)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotation', to='plantapp.seasonalharvesting')),
            ],
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Technique',
        ),
    ]
