# Generated by Django 5.1.5 on 2025-02-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0015_remove_technique_crop_croprotation_delete_season_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropRotation',
        ),
    ]
