# Generated by Django 5.1.5 on 2025-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0016_delete_croprotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suitable_months', models.JSONField()),
                ('season_text', models.TextField()),
            ],
        ),
    ]
