# Generated by Django 5.1.5 on 2025-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0017_croprotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprotation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalharvesting',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
