# Generated by Django 5.1.5 on 2025-03-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0019_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='water_per_day',
            field=models.FloatField(default=1.0),
        ),
    ]
